server:
  port: 8888 # 服务端口号

#spring:
#  application:
#    name: xiaohongshu-auth # 应用名称
#  profiles:
#    active: dev # 默认激活 dev 本地开发环境
#  cloud:
#    nacos:
#      config:
#        server-addr: nacos-server:8848 # 指定 Nacos 配置中心的服务器地址
#        prefix: ${spring.application.name} # 配置 Data Id 前缀，这里使用应用名称作为前缀
#        group: DEFAULT_GROUP # 所属组
#        namespace: public # 命名空间
#        file-extension: yaml # 配置文件格式
#        refresh-enabled: true # 是否开启动态刷新


#nacos:
#  config: # Nacos 配置中心
#    access-key: # 身份验证
#    secret-key: # 身份验证
#    data-id: xiaohongshu-auth # 指定要加载的配置数据的 Data Id
#    group: DEFAULT_GROUP # 指定配置数据所属的组
#    type: yaml # 指定配置数据的格式
#    server-addr: nacos-server:8848/ # 指定 Nacos 配置中心的服务器地址
#    auto-refresh: true # 是否自动刷新配置
#    remote-first: true # 是否优先使用远程配置
#    bootstrap:
#      enable: true # 启动时，预热配置